name: exam
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  dart_code_metrics: ^5.7.5
  flutter:
    sdk: flutter
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
